Use toolkit actions
okfn/ckanext-unhcr pull request #574
Opened 2021-05-27 18:33 UTC by avdata99

Related to #511. 
Probably a final fix

2021-05-28 16:22 UTC, chris48s requested changes
I know the CKAN 2.9 branch is a bit of a pain to work on right now as there are still some outstanding PRs for the failing tests, but this PR introduces a lot of new build failures.
We will get the build for this branch green next week to make this more obvious and easier to work on.


I think if you also want to take on https://github.com/okfn/ckanext-unhcr/issues/558 as well as https://github.com/okfn/ckanext-unhcr/issues/511 that's fine, but I don't think we should do it all in one PR. Lets try and address these changes in smaller chunks. A PR that changes so much in one go is really hard and time-consuming to manually test/review. There's so much change going on here to validate.

2021-05-28 16:22 UTC, chris48s commented on ckanext/unhcr/auth.py
> +    return toolkit.get_action('package_create')(context, data_dict)
None of these changes to the auth file will work because you're replacing calls to auth functions with calls to actions.
Tbh, I'm not 100% sure what the best practice is for auth (/cc @amercader ?) but if you want to replace the calls to core auth functions with `toolkit` calls, one option is to use `@chained_auth_function` / `next_auth` if we need to call the parent.

Another is to do something like

https://github.com/okfn/ckanext-unhcr/blob/b1152c47119202ee140108e5e43de9cbaa3f1181/ckanext/unhcr/auth.py#L194-L199

if we need to call another auth function. Remember in CKAN the auth functions themselves return `{'success': False}` if the action is not allowed, but `toolkit.check_access()` raises a `NotAuthorized` so we can't `return toolkit.check_access(...)` in auth functions.

2021-05-31 12:56 UTC, avdata99 commented on ckanext/unhcr/auth.py
> +    return toolkit.get_action('package_create')(context, data_dict)
You are right @chris48s. I disn't realize those are auth and not action calls.
I fixed it [here](https://github.com/okfn/ckanext-unhcr/pull/574/commits/66d72103b0b3526327b22eef75247d5acedf201b)

2021-05-31 13:19 UTC, avdata99 commented on ckanext/unhcr/auth.py
> +    return toolkit.get_action('package_create')(context, data_dict)
I'm seeing [some heavy conflicts](https://github.com/okfn/ckanext-unhcr/pull/574/conflicts) with [your work](https://github.com/okfn/ckanext-unhcr/commit/37454dec702c3f25b966b5ef40104e3344102882) @chris48s  
My plan is to preserve your changes and validate the chained functions still works.
Is this the right approach?

2021-06-02 09:39 UTC, chris48s commented on ckanext/unhcr/auth.py
> +    return toolkit.get_action('package_create')(context, data_dict)
Yes. One of the reasons I didn't pick https://github.com/okfn/ckanext-unhcr/issues/558 as an issue to work on is because I knew there would be big conflicts with https://github.com/okfn/ckanext-unhcr/pull/553 . That PR removes quite a lot of actions we don't need any more in CKAN 2.9 and also covers a lot of the conversions to chained actions.

Your approach sounds right. Accept those changes and see what is left. After that PR I think only
- `package_update`
- `organization_create`
- `organization_member_create`
- `organization_member_delete` and
- `organization_list_all_fields`

will need any changes in the actions file.

2021-06-02 09:40 UTC, chris48s commented on ckanext/unhcr/auth.py
> +    result = toolkit.check_access('organization_create')(context, data_dict)
If you're going to call `check_access` in an auth function I think the auth function should still return a value if `check_access` throws. See the example in https://github.com/okfn/ckanext-unhcr/pull/574#discussion_r641670157

2021-06-02 16:58 UTC, avdata99 commented on ckanext/unhcr/auth.py
> +    return toolkit.get_action('package_create')(context, data_dict)
The rebase is done. Also updated tests @chris48s

2021-06-04 12:51 UTC, chris48s commented on ckanext/unhcr/auth.py
> +        result = next_auth(context, data_dict)
If we're just calling `next_auth()` in a chained function it returns a dict.
It is only if we call `toolkit.check_access()` that `{'success': False}` is wrapped as an exception instead of returning: https://github.com/ckan/ckan/blob/ckan-2.9.3/ckan/logic/__init__.py#L311-L313
(I know this is a bit confusing  )

2021-06-04 12:51 UTC, chris48s commented on ckanext/unhcr/tests/pt/test_schema.py
> +        errors = e.value.error_dict['resources'][0]
Unfortunately the fix for this is not so simple - the test is not failing because the assertion is wrong. The test is correct, but CKAN 2.9 introduces a bug in the validation which needs to be fixed upstream.
@amercader wants to pick it up so I submitted a failing test case at https://github.com/ckan/ckan/pull/6119 and it is with @amercader to work on. My proposed solution is that we skip the test for now to get the build green (PR https://github.com/okfn/ckanext-unhcr/pull/587 ) and then re-enable it once we've got a serviceable core patch we can apply. Can we back this commit out please.

2021-06-10 17:26 UTC, avdata99 commented on ckanext/unhcr/tests/pt/test_schema.py
> +        errors = e.value.error_dict['resources'][0]
Changed [here](https://github.com/okfn/ckanext-unhcr/pull/574/commits/02108ffaf101a6eef8ce486fb6f79c74c2320597)
I rebased this branch and now the test is green

2021-06-10 17:46 UTC, avdata99 commented on ckanext/unhcr/auth.py
> +        result = next_auth(context, data_dict)
I just [make a change](https://github.com/okfn/ckanext-unhcr/pull/574/commits/ffae220236938b5be56a8f29af479d84cb963d63) that fixed this error

2021-06-11 14:10 UTC, chris48s commented on ckanext/unhcr/auth.py
> +        result = next_auth(context, data_dict)
This is another situation where we are clearly struggling to communicate. Sorry if the previous explanation is unclear.

Calling `next_auth` returns a dict if auth fails (just like this function does) because we're invoking the auth function directly. There is no exception to catch.

The block should be:

```py
    result = next_auth(context, data_dict)
    if not result['success']:
        return result
```

The case where we need to catch `toolkit.NotAuthorized` would be if we were calling `toolkit.check_access()` but That isn't what we are doing here.

2021-06-14 14:37 UTC, avdata99 commented on ckanext/unhcr/auth.py
> +        result = next_auth(context, data_dict)
My bad @chris48s . 
Fixed [here](https://github.com/okfn/ckanext-unhcr/pull/574/commits/97f490ca7f1a4b49e916735d4a6c838352b66579). 
I misunderstood your message.

2021-06-15 13:53 UTC, chris48s commented on ckanext/unhcr/tests/pt/test_schema.py
> +            'process_status': 'anonymized',
Adding these fields to this resource where the resource is `'type': 'attachment'` doesn't really make sense. They are not part of the schema for attachment resources:

![Screenshot at 2021-06-15 14-15-48](https://user-images.githubusercontent.com/6025893/122064834-5b6ee380-cde9-11eb-97c1-39671da252bb.png)


Aside from that, this PR is good to go and it needed rebasing on to master to be mergeable anyway. So what I've done is I backed out this change, squashed this all into one commit: 03f0275 and I've pushed that to master. I will mark the PR "closed" but it is really merged.

2021-06-15 13:53 UTC, closed without merging