Move visibility field from dataset to resources
okfn/ckanext-unhcr pull request #628
Opened 2021-07-13 18:11 UTC by avdata99

Replaces #583 (now based on master and squashed)
Related to #581

This PR:
 - Copy field definition from dateset to resource (required only at resource level)
 - Remove `visibility` field from dataset form
 - Add `visibility` field to resources form
 - Adds a migration script to copy `visibility` values from datasets to resources
 - Include [ckanextt-ddi PR](https://github.com/okfn/ckanext-ddi/pull/8) to import and take care of visibility for new resources

2021-07-13 18:13 UTC, avdata99 commented on ckanext/unhcr/helpers.py
> +    return not access_already_requested
Helper to use in the UI to define whether the access request form should be available

2021-07-13 18:14 UTC, avdata99 commented on ckanext/unhcr/jobs.py
> +        package_weight = weights.get(package.get(key), 0)
"Visibility" is no longer a required field, so it may not be present.

2021-07-13 18:30 UTC, avdata99 commented on ckanext/unhcr/validators.py
> +        raise Invalid('Invalid value for the visibility field')
@chris48s It is not clear how visibility='private', should work now that visibility is for resources and just a replica within datasets.
We still have the visibility_validator for datasets but this behavior will be overridden by the resources visibility

2021-07-14 09:20 UTC, chris48s commented on ckanext/unhcr/validators.py
> +        raise Invalid('Invalid value for the visibility field')
I think at the resource level it is ok to do what you've done here and just say that only `'restricted'` and `'public'` are the allowed values as it is a completely new field and there is no established meaning of a `'private'` resource in CKAN.

2021-07-16 09:18 UTC, chris48s commented
I had another look over this today. Aside from getting the background job working with package_revise I think this is done (although I think we should just pull that work into this branch - I'll comment on #629

2021-07-20 10:53 UTC, chris48s approved these changes
Ready to go, but again we need to get py3 to production or deploy from a different branch before we merge it

2021-07-22 10:20 UTC, chris48s requested changes
@avdata99
Now that we've merged #622 to master we need to make a small update to this PR to get the migrations into the right order. Can you:
- Rebase this branch onto master
- Rename `004_0a7c08639f19_visibility_for_resources.py` to `005_0a7c08639f19_visibility_for_resources.py`
- Change the `down_revision` in that migration to `65d2d180530c`

Thanks :+1:

2021-07-22 12:00 UTC, avdata99 commented
@chris48s: Rebased and updated [here](https://github.com/okfn/ckanext-unhcr/pull/628/commits/f3065f20bcd43264fd9db4da18d06770e155d02e)

2021-07-22 13:41 UTC, chris48s approved these changes
nice - thanks

2021-07-28 15:18 UTC, merged